/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cadastrocliente;

/**
 *
 * @author ibarboza_faeterj-pet
 */
public class IncluirCliente extends javax.swing.JDialog {

    /**
     * Creates new form IncluirCliente
     */
    public IncluirCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        logradouro = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        complemento = new javax.swing.JLabel();
        bairro = new javax.swing.JLabel();
        cidade = new javax.swing.JLabel();
        CEP = new javax.swing.JLabel();
        entEstado = new javax.swing.JComboBox<>();
        entNome = new javax.swing.JTextField();
        entTel = new javax.swing.JTextField();
        entEmail = new javax.swing.JTextField();
        entLogra = new javax.swing.JTextField();
        entNum = new javax.swing.JTextField();
        entComplemento = new javax.swing.JTextField();
        entBairro = new javax.swing.JTextField();
        entCidade = new javax.swing.JTextField();
        entCEP = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nome.setText("Nome:");

        telefone.setText("Telefone:");

        email.setText("Email:");

        logradouro.setText("Logradouro:");

        numero.setText("Número:");

        complemento.setText("Complemento:");

        bairro.setText("Bairro:");

        cidade.setText("Cidade:");

        CEP.setText("CEP:");

        entEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", " ", " ", "Pará (PA): paraense", " ", " ", "Paraíba (PB): paraibano", " ", " ", "Paraná (PR): paranaense", " ", " ", "Pernambuco (PE): pernambucano", " ", " ", "Piauí (PI): piauiense", " ", " ", "Rio de Janeiro (RJ): fluminense (carioca é quem é da cidade do Rio de Janeiro)", " ", " ", "Rio Grande do Norte (RN): potiguar ou norte-rio-grandense", " ", " ", "Rio Grande do Sul (RS): gaúcho ou sul-rio-grandense", " ", " ", "Rondônia (RO): rondoniano ou rondoniense", " ", " ", "Roraima (RR): roraimense", " ", " ", "Santa Catarina (SC): catarinense ou barriga-verde", " ", " ", "São Paulo (SP): paulista (quem é da capital é paulistano)", " ", " ", "Sergipe (SE): sergipano", " ", " ", "Tocantins (TO): tocantinense" }));
        entEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entEstadoActionPerformed(evt);
            }
        });

        entNome.setText("Digite o nome...");
        entNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entNomeActionPerformed(evt);
            }
        });

        entTel.setText("Digite o telefone...");
        entTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entTelActionPerformed(evt);
            }
        });

        entEmail.setText("Digite o email...");
        entEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entEmailActionPerformed(evt);
            }
        });

        entLogra.setText("Digite o logradouro...");
        entLogra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entLograActionPerformed(evt);
            }
        });

        entNum.setText("Digite o numero...");
        entNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entNumActionPerformed(evt);
            }
        });

        entComplemento.setText("Digite o complemento...");
        entComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entComplementoActionPerformed(evt);
            }
        });

        entBairro.setText("Digite o bairro...");
        entBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entBairroActionPerformed(evt);
            }
        });

        entCidade.setText("Digite a cidade...");
        entCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entCidadeActionPerformed(evt);
            }
        });

        entCEP.setText("12345-678");
        entCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entCEPActionPerformed(evt);
            }
        });

        estado.setText("Estado:");

        jButton1.setText("Ok");

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CEP)
                    .addComponent(cidade)
                    .addComponent(bairro)
                    .addComponent(complemento)
                    .addComponent(telefone)
                    .addComponent(email)
                    .addComponent(logradouro)
                    .addComponent(numero)
                    .addComponent(nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(entNome)
                    .addComponent(entTel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entEmail)
                    .addComponent(entLogra)
                    .addComponent(entNum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entComplemento)
                    .addComponent(entBairro)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(entCidade)
                            .addComponent(entCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(estado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(entNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefone)
                    .addComponent(entTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(entEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logradouro)
                    .addComponent(entLogra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero)
                    .addComponent(entNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complemento)
                    .addComponent(entComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bairro)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidade)
                            .addComponent(entEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CEP)
                            .addComponent(entCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(entBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entEstadoActionPerformed

    private void entNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entNomeActionPerformed

    private void entTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entTelActionPerformed

    private void entEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entEmailActionPerformed

    private void entLograActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entLograActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entLograActionPerformed

    private void entNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entNumActionPerformed

    private void entComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entComplementoActionPerformed

    private void entBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entBairroActionPerformed

    private void entCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entCidadeActionPerformed

    private void entCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entCEPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncluirCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IncluirCliente dialog = new IncluirCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEP;
    private javax.swing.JLabel bairro;
    private javax.swing.JLabel cidade;
    private javax.swing.JLabel complemento;
    private javax.swing.JLabel email;
    private javax.swing.JTextField entBairro;
    private javax.swing.JTextField entCEP;
    private javax.swing.JTextField entCidade;
    private javax.swing.JTextField entComplemento;
    private javax.swing.JTextField entEmail;
    private javax.swing.JComboBox<String> entEstado;
    private javax.swing.JTextField entLogra;
    private javax.swing.JTextField entNome;
    private javax.swing.JTextField entNum;
    private javax.swing.JTextField entTel;
    private javax.swing.JLabel estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel logradouro;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
